### ISSUE TITLE
Gem unupdated ?!

### ISSUE THREAD

**Issue by joel** [jviney/acts_as_taggable_on_steroids#12]
Hi,

I have DEPRECATION WARNING: Object#returning has been deprecated in favor of Object#tap. (called from from at /opt/local/lib/ruby/gems/1.8/gems/acts_as_taggable_on_steroids-1.2/lib/tag_list.rb:87) with gem 1.2 and Rails 2.3..9, but I see the file, tag_list.rb, is different with github repository.

Updating your Gem is expected when?

Thanks

**Comment by jviney** [comment]
Github are no longer publishing gems. This has been fixed in master, please clone that to get the fix.

**Comment by joel** [comment]
humm ... I do not understand the remark. Ok gems are hosted by gemcutter.org but it's still your code?! Or do I not understand?

https://rubygems.org/gems/acts_as_taggable_on_steroids

**Comment by jviney** [comment]
I didn't post that gemcutter gem, and don't have permission to update it ....
