### ISSUE TITLE
tag_counts overwrites standard find() method

### ISSUE THREAD

**Issue by seven1m** [jviney/acts_as_taggable_on_steroids#13]
Line 139 of acts_as_taggable.rb calls scope(:find) which overwrites the standard find method in Rails 3, causing all subsequent calls to find() on that model to return a scope (relation).

I'm not familiar enough with the code to know what the scope call is supposed to be doing -- otherwise I'd submit a patch.

**Comment by snicky** [comment]
Did you find a fix? I still have the same problem.

**Comment by seven1m** [comment]
I just commented it out, since it seemed unnecessary for my purposes: https://github.com/seven1m/onebody/commit/8ca3adb56a9ea09a4f47ed057efd5d79b5a90fd0

**Comment by seven1m** [comment]
Closing this issue as I no longer use this fork.

My fork is [here](https://github.com/seven1m/acts_as_taggable_on_steroids) and works ok for me on Rails 4.x.
