### ISSUE TITLE
Problem querying by tag and ordering "Random()"  using postgres

### ISSUE THREAD

**Issue by bstingle** [jviney/acts_as_taggable_on_steroids#17]
Postgres is complaining due to the order by Random() at the end of my query.  it wants that included in the select clause inside "find_options_for_find_tagged_with".   I can't figure out how to include this,  and don't think I want to - it sounds like the result would be that the objects I return would no longer be dinstinct.   See my post on Stackoverflow for a more clear explanation:

http://stackoverflow.com/questions/4721094/acts-as-taggable-on-steroids-query-failing-on-postgres

thanks!  love this plugin.

**Comment by jviney** [comment]
I suggest trying the acts-as-taggable-on plugin which is more actively developed and maintained.

**Comment by bstingle** [comment]
thanks!
