### ISSUE TITLE
:match_all bug?

### ISSUE THREAD

**Issue by gordonbisnor** [jviney/acts_as_taggable_on_steroids#2]
I found that :match_all => true did not seem to be working for me - I was getting the same result set as when I did not use it. I don’t know if there is a unique circumstance on my end that is causing the problem (I just imported data from a legacy database and there may have been some weirdness in the data that would not be present if the data had been generated by the plugin itself),  or maybe there is an issue with the plugin. I changed line 90 of lib/acts_as_taggable.rb to this:

```
(SELECT COUNT(DISTINCT tags.id) FROM #{Tagging.table_name}
```

That seems to work for me.

**Comment by jviney** [comment]
Were you using :exclude as well? Do you have the latest version of the plugin?

**Comment by jviney** [comment]
Confirmed as working with latest plugin version.
