### ISSUE TITLE
undefined local variable or method `acts_as_taggable'

### ISSUE THREAD

**Issue by matenia** [jviney/acts_as_taggable_on_steroids#4]
I have included this as a plugin and put
acts_as_taggable in my Post model, however still get the error
undefined local variable or method `acts_as_taggable'
do I have to include the original acts_as_taggable gem in my environment?
I have scoured the web and found alot of mentions of this error but no solution.
any ideas?

**Comment by jviney** [comment]
Please try asking on the Rails mailing list. You could also try the plugin acts_as_taggable_on.

**Comment by matenia** [comment]
I managed to fix it by doing the following, which is sort of ok but not how it should be.

I performed the task            gem install acts_as_taggable_on_steroids
then did         require 'acts_as_taggable_on_steroids'            in the environment.rb file after the "end" tag and it got me past the first hurdle of having the definition of acts_as_taggable_on moving on from here.
